name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get short SHA
        id: get-short-sha
        run: |
          id=$(echo ${{github.sha}} | cut -c 1-7)
          echo "::set-output name=id::$id"
      - name: Extract commit title and description
        id: extract_commit
        run: |
          COMMIT_TITLE=$(echo "${{ github.event.head_commit.message }}" | awk 'NR==1')
          COMMIT_DESCRIPTION=$(echo "${{ github.event.head_commit.message }}" | awk 'NR>2')
          echo "::set-output name=COMMIT_TITLE::$COMMIT_TITLE"
          echo "::set-output name=COMMIT_DESCRIPTION::$COMMIT_DESCRIPTION"
      - name: Read JSON file and replace placeholders
        run: |
          sed -i "s#{event_type}#${{ github.event_name }}#g" workflow_data/embed.json
          sed -i "s#{commit_title}#${{steps.extract_commit.outputs.COMMIT_TITLE}}#g" workflow_data/embed.json
          sed -i "s#{commit_description}#${{steps.extract_commit.outputs.COMMIT_DESCRIPTION}}#g" workflow_data/embed.json
          sed -i "s#{commit_id}#${{steps.get-short-sha.outputs.id}}#g" workflow_data/embed.json
          sed -i "s#{branch}#${{ github.ref_name}}#g" workflow_data/embed.json
          sed -i "s#{branch_url}#${{ github.ref.url}}#g" workflow_data/embed.json
          sed -i "s#{repository_owner}#${{ github.event.repository.owner.name }}#g" workflow_data/embed.json
          sed -i "s#{repository}#${{ github.event.repository.name }}#g" workflow_data/embed.json
          sed -i "s#{repository_url}#${{ github.event.repository.html_url }}#g" workflow_data/embed.json
          sed -i "s#{event_compare}#${{ github.event.compare }}#g" workflow_data/embed.json
          sed -i "s#{actor}#${{ github.event.sender.login }}#g" workflow_data/embed.json
          sed -i "s#{actor_url}#${{ github.event.sender.html_url }}#g" workflow_data/embed.json
          sed -i "s#{actor_avatar}#${{ github.event.sender.avatar_url }}#g" workflow_data/embed.json
          sed -i "s#{timestamp}#${{ github.event.head_commit.timestamp }}#g" workflow_data/embed.json
      - name: Send Discord Webhook Action
        uses: tsickert/discord-webhook@v5.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: workflow_data/embed.json