name: Discord Notification

on:
  push:
    branches:
      - main
env:
  COMMIT_TITLE: ''
  COMMIT_DESCRIPTION: ''

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Extract commit title and description
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          export COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +3)
      - name: Read JSON file and replace placeholders
        run: |
          sed -i "s/{commit_title}/${{ env.COMMIT_DESCRIPTION }}/g" embed.json
          sed -i "s/{commit_description}/${{ env.COMMIT_DESCRIPTION }}/g" embed.json
          sed -i "s/{repository_owner}/${{ github.repository_owner }}/g" embed.json
          sed -i "s/{repository}/${{ github.repository }}/g" embed.json
          sed -i "s/{repository_url}/${{ github.repositoryUrl }}/g" embed.json
          sed -i "s/{event_compare}/${{ github.event.compare }}/g" embed.json
          sed -i "s/{commit_title}/${{ env.COMMIT_TITLE }}/g" embed.json
          sed -i "s/{actor}/${{ github.actor }}/g" embed.json
          sed -i "s/{actor_url}/${{ github.actor.url }}/g" embed.json
          sed -i "s/{actor_avatar}/${{ github.actor.avatar_url }}/g" embed.json
          sed -i "s/{timestamp}/${{ github.event.head_commit.timestamp }}/g" embed.json
      - name: Send Discord Webhook Action
        uses: tsickert/discord-webhook@v5.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: workflow_data/embed.json