name: Discord Notification

on:
  push:
    branches:
      - main
env:
  COMMIT_TITLE: ''
  COMMIT_DESCRIPTION: ''

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Extract commit title and description
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          export COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +3)
      - name: Send Discord Webhook Action
        uses: tsickert/discord-webhook@v5.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: workflow_data/embed.json