name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: ${{ github.event.head_commit.message }}
          embed-description: "Commit description: ${{ github.event.head_commit.description }}"
          embed-author-name: ${{ github.event.sender.login }}
          embed-author-icon-url: ${{ github.event.sender.avatar_url }}
          embed-footer-text: "Commit Time"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
