name: Discord Notification

on:
  push:
    branches:
      - main
env:
  COMMIT_TITLE: ''
  COMMIT_DESCRIPTION: ''

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract commit title and description
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          export COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +3)
      - name: Read JSON file and replace placeholders
        run: |
          sed -i "s#{commit_title}#TEST COMMIT TITLE#g" workflow_data/embed.json
          sed -i "s#{commit_description}#TEST COMMIT DESCRIPTION#g" workflow_data/embed.json
          sed -i "s#{repository_owner}#${{ github.event.repository.owner }}#g" workflow_data/embed.json
          sed -i "s#{repository}#${{ github.event.repository.name }}#g" workflow_data/embed.json
          sed -i "s#{repository_url}#${{ github.event.repository.html_url }}#g" workflow_data/embed.json
          sed -i "s#{event_compare}#${{ github.event.compare }}#g" workflow_data/embed.json
          sed -i "s#{actor}#${{ github.event.sender.login }}#g" workflow_data/embed.json
          sed -i "s#{actor_url}#${{ github.event.sender.html_url }}#g" workflow_data/embed.json
          sed -i "s#{actor_avatar}#${{ github.event.sender.avatar_url }}#g" workflow_data/embed.json
          sed -i "s#{timestamp}#${{ github.event.head_commit.timestamp }}#g" workflow_data/embed.json
      - name: Send Discord Webhook Action
        uses: tsickert/discord-webhook@v5.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: workflow_data/embed.json