name: Discord No Raw Notification

on:
  push:
    branches:
      - main
env:
  COMMIT_TITLE: ''
  COMMIT_DESCRIPTION: ''

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract commit title and description
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          export COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +3)
      - name: Send Discord Webhook Action
        uses: tsickert/discord-webhook@v5.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: ${{ github.event.repository.name }}
          embed-url: ${{ github.event.repository.html_url }}
          embed-description: ${{ github.event.head_commit.message }} \n\n\n test
          embed-author-name: ${{ github.event.sender.login }}
          embed-author-icon-url: ${{github.event.sender.avatar_url}}
          embed-author-url: ${{ github.event.sender.html_url }}
          embed-thumbnail-url: ${{github.event.sender.avatar_url}}
          embed-footer-text: "Commit Timestamp"
          embed-color: 4757759
          embed-timestamp: ${{ github.event.head_commit.timestamp }}